# Generated by Django 5.1.1 on 2024-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classiccorner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='Unspecified', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1000', max_digits=10),
        ),
    ]
