# Generated by Django 5.1.1 on 2024-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classiccorner', '0002_item_category_item_image_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
