# Generated by Django 5.1.1 on 2024-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classiccorner', '0003_alter_item_category_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
