# Generated by Django 5.1.1 on 2024-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classiccorner', '0004_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
